version: '3.2'
services:
  nginx-reverse-proxy:
    image: nginx-reverse-proxy:1
    environment:
      - NGINX_INTEGARATIONS_EPIC_ENCRYPT_URL=localhost:3001
      - NGINX_INTEGARATIONS_EPIC_URL=localhost:3001
      - NGINX_ROOT_URL=localhost:3001
      - NGINX_SUPERADMIN_URL=127.0.0.1:3011
      - NGINX_SOCKETIO_URL=localhost:3001
      - NGINX_SSL_REWRITE_PORT=8080
      - NGINX_PROXY_PORT=80
